config/routes.rb
Thingslist::Application.routes.draw do
  get 'users/sign_in' => redirect('/users/auth/facebook')
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :categories
  resources :ads
  
  resources :city do
    collection do
      get 'search'
    end
  end
  
  get 'redirect' => 'home#redirect'

  # Api Paths

  namespace :api do
    resources :categories do
      collection do
        get 'parents'
        get 'children'
      end
    end

    resources :cities do
      collection do
        get 'nearby'
        get 'search'
      end
    end

    resources :ads do
    end
  end

  get 'fbobject' => 'home#fbobject'
  root :to => 'home#index'
end

app/models/ad.rb
class FbValidValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    if not value or value.facebook_valid == false
      record.errors[attribute] << (options[:message] || "is not valid")
    end
  end
end

class Ad
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::FullTextSearch

  @@QUALITY_OPTIONS = ['new','used', 'refurbished', 'not working']
  cattr_reader :QUALITY_OPTIONS

  belongs_to :city
  belongs_to :category
  belongs_to :user
  
  field :title
  field :description
  field :price
  field :quality

  validates :title, :presence => true
  validates :description, :presence => true
  validates :user, :presence => true, :fb_valid => true
  validates :city, :presence => true
  validates :quality, :inclusion => { 
                        :in => Ad.QUALITY_OPTIONS, 
                        :allow_blank => true 
                      }

  fulltext_search_in :title, :description

  def price
    price = Money.new(read_attribute(:price) || 0)
  end

  def price=(price)
    write_attribute(:price, Money.parse(price).cents)
  end

  def to_s
    title
  end

  def distance(city, unit = :mi)
    self.city.find_distance(city, unit).round(2)
  end

  def self.within(city, dist, unit = :mi)
    cities = city.find_closest(dist, unit).only(:_id).limit(100).map(&:_id)
    cities << city._id

    Ad.where(:city_id.in => cities)
  end

end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_filter :authenticate_user!, :except => :show

  def new
    cid = params[:cid] || ""
    @category = Category.where(:_id => cid).first

    if @category
      @ad = Ad.new
      render "templates/new/#{@category.template}", :layout => false
    end
  end

  def show
    @ad = Ad.find(params[:id])
    render "templates/view/#{@ad.category.template}"
  end
  
end

app/controllers/api/ads_controller.rb
class Api::AdsController < Api::ApiController

  def create
    ad = Ad.new(params[:ad])
    ad.user = current_user
    if ad.save()
      current_user.post_ad(ad)
      respond_with(true)
    else
      respond_with(ad.errors.full_messages)
    end
  end

end

app/helpers/ad_helper.rb
module AdHelper

  def price_to_text(price)
    if price.cents == 0
      "Free"
    else
      "$#{price}"
    end
  end

  def quality_to_text(quality)
    if quality.blank?
      "-"
    else
      quality.titlecase
    end
  end

end

app/helpers/api/ad_helper.rb
module Api::AdHelper
end

app/views/ads/_ad.html.slim
div.ad
  = link_to truncate(ad.title, :length => 80), ad_path(ad)
  |  - (#{ad.city}) 
  div 
    | Posted #{time_ago_in_words(ad.created_at)} ago by #{ link_to(ad.user, ad.user.profile_url) if ad.user }

    - if ad.distance(@city) > 0
      span.divider |
      span.label.label-success-light #{ad.distance(@city)} miles away

app/views/ads/new.html.slim
h1= t(:post_ad)
hr

.row
  .span4
    .well
      h4 style='margin-bottom: 5px' Select a Category
      input.categories-typeahead.typeahead type='text'

  #template_content.span7 style='margin-left: 30px'
  #animation.hide.span7 style='text-align: center;'
    = image_tag "loading.gif"

app/views/ads/show.html.slim
h3 = @ad.title
p posted #{time_ago_in_words(@ad.created_at)} ago by #{@ad.user}
hr
p == Sanitize.clean(@ad.description, Sanitize::Config::BASIC)