config/routes.rb
Thingslist::Application.routes.draw do
  get 'users/sign_in' => redirect('/users/auth/facebook')
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :categories
  resources :ads
  
  resources :city do
    collection do
      get 'search'
    end
  end
  
  get 'redirect' => 'home#redirect'

  # Api Paths

  namespace :api do
    resources :categories do
      collection do
        get 'parents'
        get 'children'
      end
    end

    resources :cities do
      collection do
        get 'nearby'
        get 'search'
      end
    end

    resources :ads do
    end
  end

  get 'fbobject' => 'home#fbobject'
  root :to => 'home#index'
end

app/views/shared/_nav.html.slim
div.navbar.navbar-fixed-top
  div.navbar-inner
    div.container
      a.btn.btn-navbar data-target=".nav-collapse" data-toggle="collapse"
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.brand href="#" = t(:site_name)
      .nav-collapse
        ul.nav
          li.active
            a href="/" = t(:"nav.home")
        ul.nav.pull-right
          li.dropdown
            a.dropdown-toggle data-toggle="dropdown" href="#"
              | #{@city} 
              b.caret
            ul.dropdown-menu
              - @city.find_closest(30).limit(10).each do |nearby_city|
                li= link_to nearby_city, city_path(nearby_city)
            li.divider-vertical
          - if current_user
            li.dropdown
              a.dropdown-toggle href='#' data-toggle='dropdown'
                | #{current_user.email} 
                b.caret
              ul.dropdown-menu
                li= link_to 'logout', destroy_user_session_path, :method => :delete
          - else
            li
              = image_tag "facebook_login.png", :class => 'facebook_button'