config/routes.rb
Thingslist::Application.routes.draw do
  get 'users/sign_in' => redirect('/users/auth/facebook')
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :categories
  resources :ads
  
  resources :city do
    collection do
      get 'search'
    end
  end
  
  get 'redirect' => 'home#redirect'

  # Api Paths

  namespace :api do
    resources :categories do
      collection do
        get 'parents'
        get 'children'
      end
    end

    resources :cities do
      collection do
        get 'nearby'
        get 'search'
      end
    end

    resources :ads do
    end
  end

  get 'fbobject' => 'home#fbobject'
  root :to => 'home#index'
end

app/models/city.rb
class City
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Spacial::Document
  include Mongoid::Slug
  include Mongoid::FullTextSearch

  belongs_to :state
  has_many :ads

  field :name
  slug :to_s

  # source = { :lng => x, :lat => y }
  # find using [lng, lat] = [x, y]
  field :source, type: Array, spacial: true

  spacial_index :source
  fulltext_search_in

  def geolocation
    geo = Geocoder.search(to_s).first
    if geo
      self.source = { :lat => geo.latitude, :lng => geo.longitude }
    end
  end

  def location
    [source[:lng], source[:lat]]
  end

  def find_closest(distance, unit=:mi)
    City.where(:source.near => 
      { :point => self.location, :max => distance, :unit => unit }).offset(1)
  end

  def find_distance(city, unit=:mi)
    self.distance_from(:source, city.location, { :unit => unit })
  end

  def to_s
    "#{name}, #{state.abbr if state}".downcase
  end

  def self.find_closest(location)
    City.where(:source.near => location).limit(1).first 
  end

  def serialize
    {
      :id => id,
      :name => name,
      :state => state.abbr
    }
  end

end

app/controllers/api/cities_controller.rb
class Api::CitiesController < Api::ApiController

  def search
    required :city
    defaults :limit => 10
    @limit = 10 if @limit > 10 or @limit < 1

    cities = City.where(:name => /#{@city}/).includes(:state).limit(@limit)
    #cities = City.fulltext_search(@city, { :max_results => @limit })

    respond_with(cities)
  end

  def nearby
    required :city, :state
    defaults :limit => 10, :distance => 30

    state = State.any_of({:name => @state}, {:abbr => @state}).first
    city = City.where(:name => @city, :state_id => state.id).first
    cities = city.find_closest(@distance).limit(@limit)

    respond_with(cities)
  end

end

app/controllers/city_controller.rb
class CityController < ApplicationController
  
  def index
  end

  def show
    @city = City.find_by_slug(params[:id]) || raise_404
    cache_city(@city)

    @categories = Category.parents()
  end

  # Need to make sure that its limited by geospatial distance
  def search
    @query = params[:q]
    @ads = Ad.within(@city, 30)
    @ads = @ads.fulltext_search(@query).group_by { |x| x.created_at.to_date }
  end

end

app/helpers/api/cities_helper.rb
module Api::CitiesHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/views/city/search.html.slim
.row
  .span3
    form method='get'
      input.search-query name='q' type='text' placeholder='Search' value='#{params[:q]}'
  .span6.center
    h2= @city
  .span2.pull-right
    a.btn.btn-info href="#{new_ad_path}" = t(:post_ad)

hr
.span9
  - unless @ads.blank?
    - @ads.each do |date, ads|
      .ad_date = date.strftime("%b %d, %Y (%a)")
      br
        - ads.each do |ad|
          = render 'ads/ad', :ad => ad
  - else
    h4.well Nothing found that matches your search query.

app/views/city/show.html.slim
.row
  .span3
    form method='get' action='#{search_city_index_path}'
      input.search-query name='q' type='text' placeholder='Search'
  .span6.center
    h2= @city
  .span3.pull-right
    a.btn.btn-info href="#{new_ad_path}" = t(:post_ad)
hr
.categories
  - @categories.each do |c|
    = render 'categories/table', :category => c